language: node_js
node_js:
  - 10
env:
  global:
    - LIBSODIUM_VERSION="1.0.16"
    - SODIUM_INC_DIR="$HOME/libsodium-$LIBSODIUM_VERSION/include"
    - SODIUM_LIB_DIR="$HOME/libsodium-$LIBSODIUM_VERSION/lib"
    - LD_LIBRARY_PATH="$SODIUM_LIB_DIR:$LD_LIBRARY_PATH"
    - PATH="$HOME/.cargo/bin:$PATH"
install:
  - ./.travis/install-rust.sh
  - ./.travis/install-libsodium.sh
  - yarn install
script:
  - yarn run lint
  - yarn run test
cache:
  cargo: true
  yarn: true
  directories:
    - node_modules
    - $HOME/libsodium-$LIBSODIUM_VERSION
    - $HOME/.rustup
